#! /usr/bin/python3

import sys, os
sys.path.insert(1, os.path.join(os.path.dirname(__file__), "..", ".."))
from pykarta.formats.osm_writer import OsmWriter
import json

infile = sys.argv[1]
outfile = sys.argv[2]

with open(infile, "r") as fh:
	geojson = json.load(fh)
fh = open(outfile, "w")
osm = OsmWriter(fh, "PyKarta geojson2osm 1.0")

if geojson['type'] == 'Feature':
	features = [geojson]
elif geojson['type'] == 'FeatureCollection':
	features = geojson['features']
else:
	assert False

for feature in features:
	assert feature['type'] == 'Feature'
	geometry = feature['geometry']
	assert geometry['type'] == 'Polygon'
	coordinates = geometry['coordinates']
	assert len(coordinates) == 1
	coordinates = coordinates[0]
	coordinates = map(lambda coordinate: (coordinate[1], coordinate[0]), coordinates)
	osm.new_way(coordinates, feature['properties'])
	
osm.save()
